"""add document file hash

Revision ID: e98190d3eed4
Revises: 9953ab2cf302
Create Date: 2026-09-11 10:48:53.237869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98190d3eed4'
down_revision: Union[str, Sequence[str], None] = '9953ab2cf302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        'documents',
        sa.Column(
            'file_hash',
            sa.String(length=64),
            nullable=True
        )
    )

    op.create_index(
        'ix_documents_file_hash',
        'documents',
        ['file_hash']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
